### ISSUE TITLE
prometheus Alertmanager Slack 알림 설정

### ISSUE THREAD

**Issue by zhtcks** [algorithm-curator/algorithm-curator#39]
## 작업 내용

- prometheus + grafana 설정 이후 prometheus Alertmanager를 사용하여 Slack 알림 설정
- 최초 알림 설정 항목경우에 알림을 받도록 설정
  - `server Status가 UP이 아닌 경우`
  - `load-average가 70%이상`인 
  - 서비스 내 인스턴스의 `API 초 당 요청 수가 20개를 초과`하는 경우

## 목차

1. 프로젝트 알림 구조
1. Alert 규칙 설정
1. 프로메테우스와 Alertmanager 연동
1. Slack 연동
1. 결과

---

## 프로젝트 알림 구조

- `algorithm-curator` 서버에서 모니터링 중인 이벤트 발생 시 해당 이벤트를 `슬랙 알림`으로 전달하는 구조

![프로젝트 아키텍쳐 generator 001](https://user-images.githubusercontent.com/75410527/181916995-b0db48b3-b4ae-4555-a370-1511e62780d8.jpeg)

## Alert 규칙 설정

- `alert_rules.yml`에 알림 규칙 정의

```yml
# alert_rules.yml

groups:
- name: alert_exporter # 그룹 이름
  rules:
  - alert: 'Api Server Down' # 알림 이름
    expr: up{instance="apcurator.net:XXXXX",job="apcurator_node"} == 0 # 알림 조건 설정(alert의 평가식)
    for: 5m # for에서 지정한 시간 동안 expr 조건을 충족하게 되면 알림을 보냅니다.
    labels: # 필요한 label들을 설정할 수 있다
      severity: critical
    annotations:
      summary: "Api Service {{ $labels.instance }} down"
      description: "{{ $labels.instance }} has been down for more than 5 minutes."

  - alert: 'Log Server Down' # 알림 이름
    expr: up{instance="apcurator.net:XXXXX",job="apcurator_node"} == 0 # 알림 조건 설정(alert의 평가식)
    for: 5m # for에서 지정한 시간 동안 expr 조건을 충족하게 되면 알림을 보냅니다.
    labels: # 필요한 label들을 설정할 수 있다
      severity: critical
    annotations:
      summary: "Log Service {{ $labels.instance }} down"
      description: "{{ $labels.instance }} has been down for more than 5 minutes."

  - alert: 'Api Server load_average alert' # 알림 이름
    expr: system_load_average_1m{instance="apcurator.net:XXXXX",job="apcurator_node"} > 0.7 # 알림 조건 설정(alert의 평가식)
    for: 1m
    labels: # 필요한 label들을 설정할 수 있다
      severity: critical
    annotations:
      summary: "{{ $labels.job }} {{ $labels.instance }}"
      description: "{{ $labels.instance }}의 load_average가 70%를 초과합니다. (current value: {{ humanize $value }}"

  - alert: 'Log Server load_average alert' # 알림 이름
    expr: system_load_average_1m{instance="apcurator.net:XXXXX",job="apcurator_node"} > 0.7 # 알림 조건 설정(alert의 평가식)
    for: 1m
    labels: # 필요한 label들을 설정할 수 있다
      severity: critical
    annotations:
      summary: "{{ $labels.job }} {{ $labels.instance }}"
      description: "{{ $labels.instance }}의 load_average가 70%를 초과합니다. (current value: {{ humanize $value }}"

  - alert: 'Api Server Http Request per second' # 알림 이름
    expr: irate(http_server_requests_seconds_count{job="apcurator_node", instance="apcurator.net:XXXXX"}[3m]) > 20 # 초당 알림 조건 설정(alert의 평가식)
    for: 3m
    labels: # 필요한 label들을 설정할 수 있다
      severity: critical
    annotations:
      summary: "{{ $labels.job }} {{ $labels.instance }}"
      description: "{{ $labels.instance }}의 초당 http 요청 갯수가 20을 초과합니다. (current value: {{ humanize $value }}"
```

## 프로메테우스와 Alertmanager 연동

- 기존의 `prometheus.yml`에 Alertmanager 설정 추가

```yml
# Alertmanager와 프로메테우스를 연결하기 위해 설정 추가
# 현재 로컬에서 9093 포트를 통해 alertmanager가 구동되고 있음
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
        
# 어떤 경우에 알람이 발생할 것인지 규칙을 정해놓은 rules 파일 설정
rule_files:
  - "alert_rules.yml"
```

## Slack 연동

- 아래의 `alertmanager.yml` 설정으로 Alertmanager 재실행 

```bash
sudo systemctl restart prometheus-alertmanager
```

```yml
# alertmanager.yml

global:
  slack_api_url: 'https://hooks.slack.com/services/XXX/YYY/ZZZ'

# The root route on which each incoming alert enters.
route: # 라우트 경로 설정

  # 경고를 모으기 위한 간격 설정
  group_wait: 30s  # inhibit 조건 발생에 대한 중복을 방지하기 위한 알림 발생 전 대기시간, 
  group_interval: 5m # 알림 간 시간 간격 설정
  repeat_interval: 30m # 알림 재발생

  # default receiver의 설정
  receiver: 'slack-notifications' # 알림 설정 대상

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring'
    send_resolved: true
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
```

## 결과

- 프로메테우스와 Alertmanager 연동 완료

![스크린샷 2022-07-30 오후 9 52 43](https://user-images.githubusercontent.com/75410527/181916082-87f5923b-ccde-46d2-a5e1-a1543773975f.png)

- Slack 알림 결과

![스크린샷 2022-07-30 오후 10 14 59](https://user-images.githubusercontent.com/75410527/181916075-1a4fa30a-3c51-40e1-a817-d710a19fc69d.png)

---

- 참고
  - [Prometheus - webhook 설정하기(with alertmanager)](https://real-dongsoo7.tistory.com/143)
  - [알람 파이프라인 구축하기](https://gurumee92.tistory.com/255)
  - [안정적인 운영을 완성하는 모니터링, 프로메테우스와 그라파나](https://velog.io/@moey920/%EC%95%88%EC%A0%95%EC%A0%81%EC%9D%B8-%EC%9A%B4%EC%98%81%EC%9D%84-%EC%99%84%EC%84%B1%ED%95%98%EB%8A%94-%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81.-%ED%94%84%EB%A1%9C%EB%A9%94%ED%85%8C%EC%9A%B0%EC%8A%A4%EC%99%80-%EA%B7%B8%EB%9D%BC%ED%8C%8C%EB%82%98)
