### ISSUE TITLE
로그 모니터링 적용(loki와 promtail 서버 분리)

### ISSUE THREAD

**Issue by zhtcks** [algorithm-curator/algorithm-curator#54]
## 작업 내용

promtail와 loki 서버 분리

- promtail: `algorithm-curator 서버`에 있도록 설정
- loki: `모니터링 서버`에 있도록 설정
- [Grafana Loki 적용기](https://cotchan.github.io/todayilearned/2022/07/19/til-grafana-loki.html)

## 목차

1. Promtail와 Loki 서버 분리 이유
1. Promtail 설정
1. Loki 설정
1. 결과 화면

---

## Promtail와 Loki 서버 분리 이유

- 기존 프로젝트에서 `Promtail`와 `Loki`를 함께 운영중인 애플리케이션 서버에 두고, `grafana`만 분리했었는데 애플리케이션 서버에 문제가 생기니 로그 조회를 아예 못하는 현상 발생
- 그래서 grafana의 `dataSource`인 `loki`도 애플리케이션 서버와 분리해야 문제 상황 시 서버 로그 분석이 가능할 것이라 판단

## Promtail 설정

- 로그 수집기인 `Promtail`은 애플리케이션 운영 서버에 존재
- `Promtail`에서 모니터링 서버의 `Loki`에 수집중인 로그를 보내도록 설정 변경
- `localhost:3100` 설정을 원격 서버로 변경

```yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://MONITORING-SERVER.net:3100/loki/api/v1/push

scrape_configs:
- job_name: server-log
  static_configs:
  - targets:
      - MONITORING-SERVER.net
    labels:
      job: server-log
      __path__: /tmp/log/*log
```

## Loki 설정

- `Loki` 설정은 설치 시 생성되는 기본 설정에서 변경하지 않음

## 결과 화면

<img width="1787" alt="스크린샷 2022-08-10 오전 10 51 17" src="https://user-images.githubusercontent.com/75410527/183793020-933687a6-a279-4baa-b782-a611fc1683e6.png">
